---
meta:
  ocfp:
    env:
      cloud: (( concat genesis.env "." genesis.type "." ))

params:
  garage_network:   (( concat meta.ocfp.env.cloud "net-garage" ))
  garage_vm_type:   (( concat meta.ocfp.env.cloud "vm-garage" ))
  garage_disk_type: (( concat meta.ocfp.env.cloud "disk-garage" ))
